In [18]:
import pandas as pd

In [25]:
df_esquistossomose = pd.read_csv('categoriaCID-10_B65_Esquistossomose.csv', sep=';', skiprows=4, skipfooter=7, engine='python')
df_hepatite = pd.read_csv('categoriaCID-10_B15_B16_Hepatite_A_Hepatite_B.csv', sep=';', skiprows=4, skipfooter=7, engine='python')
df_leptospirose = pd.read_csv('categoriaCID-10_A27_leptospirose.csv', sep=';', skiprows=4, skipfooter=7, engine='python')
df_saneamento = pd.read_csv('Saneamento.csv', sep=';',  skiprows=3, skipfooter=1, engine='python')

#df_esquistossomose
#df_hepatite
#df_leptospirose
#df_saneamento

                                 Unidade da Federação  Cap I  Total
0                                         21 Maranhão    1.0    1.0
1                                            22 Piauí    2.0    2.0
2                                            23 Ceará    3.0    3.0
3                              24 Rio Grande do Norte    3.0    3.0
4                                          25 Paraíba   15.0   15.0
5                                       26 Pernambuco  195.0  195.0
6                                          27 Alagoas   27.0   27.0
7                                          28 Sergipe   22.0   22.0
8                                            29 Bahia   56.0   56.0
9                                     31 Minas Gerais   63.0   63.0
10                                  32 Espírito Santo   17.0   17.0
11                                  33 Rio de Janeiro   18.0   18.0
12                                       35 São Paulo   79.0   79.0
13                                          41 Paraná    4.0    4.0
14                              50 Mato Grosso do Sul    1.0    1.0
15                                     51 Mato Grosso    1.0    1.0
16                                           52 Goiás    2.0    2.0
17                                53 Distrito Federal    5.0    5.0
18                                              Total  514.0  514.0
19   Fonte: MS/SVS/CGIAE - Sistema de Informações ...    NaN    NaN
20                                              Nota:    NaN    NaN

In [26]:
list(df_esquistossomose['Unidade da Federação'].unique())
list(df_hepatite['Unidade da Federação'].unique())
list(df_leptospirose['Unidade da Federação'].unique())
list(df_saneamento['Unidade da Federação'].unique())

['11 Rondônia',
 '12 Acre',
 '13 Amazonas',
 '14 Roraima',
 '15 Pará',
 '16 Amapá',
 '17 Tocantins',
 '21 Maranhão',
 '22 Piauí',
 '23 Ceará',
 '24 Rio Grande do Norte',
 '25 Paraíba',
 '26 Pernambuco',
 '27 Alagoas',
 '28 Sergipe',
 '29 Bahia',
 '31 Minas Gerais',
 '32 Espírito Santo',
 '33 Rio de Janeiro',
 '35 São Paulo',
 '41 Paraná',
 '42 Santa Catarina',
 '43 Rio Grande do Sul',
 '50 Mato Grosso do Sul',
 '51 Mato Grosso',
 '52 Goiás',
 '53 Distrito Federal',
 'Total']

In [27]:
ufs_esquistossomose = set(df_esquistossomose['Unidade da Federação'].unique())
ufs_hepatite = set(df_hepatite['Unidade da Federação'].unique())
ufs_leptospirose = set(df_leptospirose['Unidade da Federação'].unique())
ufs_saneamento = set(df_saneamento['Unidade da Federação'].unique())

In [28]:
ufs_comuns = ufs_esquistossomose & ufs_hepatite & ufs_leptospirose & ufs_saneamento
ufs_comuns

{'21 Maranhão',
 '23 Ceará',
 '24 Rio Grande do Norte',
 '25 Paraíba',
 '26 Pernambuco',
 '27 Alagoas',
 '28 Sergipe',
 '29 Bahia',
 '31 Minas Gerais',
 '32 Espírito Santo',
 '33 Rio de Janeiro',
 '35 São Paulo',
 '41 Paraná',
 '50 Mato Grosso do Sul',
 '51 Mato Grosso',
 '53 Distrito Federal',
 'Total'}

In [29]:
df_esquistossomose_comum = df_esquistossomose[df_esquistossomose['Unidade da Federação'].isin(ufs_comuns)]
df_hepatite_comum = df_hepatite[df_hepatite['Unidade da Federação'].isin(ufs_comuns)]
df_leptospirose_comum = df_leptospirose[df_leptospirose['Unidade da Federação'].isin(ufs_comuns)]
df_saneamento_comum = df_saneamento[df_saneamento['Unidade da Federação'].isin(ufs_comuns)]

merged_df = pd.merge(df_esquistossomose_comum, df_hepatite_comum, on='Unidade da Federação', suffixes=('_esquistossomose', '_hepatite'))
merged_df = pd.merge(merged_df, df_leptospirose_comum, on='Unidade da Federação')
merged_df = pd.merge(merged_df, df_saneamento_comum, on='Unidade da Federação', suffixes=('_leptospirose', '_saneamento'))   

merged_df

,Unidade da Federação,Cap I_esquistossomose,Total_esquistossomose,Cap I_hepatite,Total_hepatite,Cap I,Total_leptospirose,Rede geral de esgoto ou pluvial,Fossa séptica,Fossa rudimendar,Vala,"Rio, lago ou mar",Outro escoadouro,Não tem instalação sanitária,Total_saneamento
0,21 Maranhão,1.0,1.0,15.0,15.0,2.0,2.0,682546,954029,2963301,529686,53047,419366,945274,6547249
1,23 Ceará,3.0,3.0,14.0,14.0,8.0,8.0,2645421,893434,3864872,151016,62331,138967,646375,8402416
2,24 Rio Grande do Norte,3.0,3.0,4.0,4.0,2.0,2.0,764356,624338,1607500,46241,11012,37584,59803,3150834
3,25 Paraíba,15.0,15.0,4.0,4.0,3.0,3.0,1436381,354990,1452847,148451,52419,80054,219624,3744766
4,26 Pernambuco,195.0,195.0,22.0,22.0,28.0,28.0,3651981,1003960,2760036,387506,271782,191588,475855,8742708
5,27 Alagoas,27.0,27.0,4.0,4.0,3.0,3.0,626417,339716,1694200,91292,61890,64745,215398,3093658
6,28 Sergipe,22.0,22.0,3.0,3.0,11.0,11.0,785090,218661,878876,45901,27738,36578,62177,2055021
7,29 Bahia,56.0,56.0,9.0,9.0,37.0,37.0,5998128,901340,4939613,398803,223375,271902,1201810,13934971
8,31 Minas Gerais,63.0,63.0,23.0,23.0,10.0,10.0,14433447,649194,2836276,223920,917428,139379,268523,19468167
9,32 Espírito Santo,17.0,17.0,7.0,7.0,1.0,1.0,2311506,233891,638354,125858,154731,15386,12914,3492640
10,33 Rio de Janeiro,18.0,18.0,34.0,34.0,64.0,64.0,11994876,1562017,960664,808617,477063,75405,17249,15895891
11,35 São Paulo,79.0,79.0,57.0,57.0,80.0,80.0,35138354,2011514,2024572,465685,1091814,187489,23772,40943200
12,41 Paraná,4.0,4.0,8.0,8.0,45.0,45.0,5408314,1247555,3411295,119217,103535,55094,33092,10378102
13,50 Mato Grosso do Sul,1.0,1.0,4.0,4.0,1.0,1.0,555206,357385,1450793,19808,3129,28150,8050,2422521
14,51 Mato Grosso,1.0,1.0,15.0,15.0,1.0,1.0,566002,498711,1832420,19910,15407,21708,54259,3008417
15,53 Distrito Federal,5.0,5.0,1.0,1.0,4.0,4.0,2005008,229008,303314,2220,433,1340,1717,2543040
16,Total,514.0,514.0,358.0,358.0,378.0,378.0,100026359,22190838,49071550,5205611,4190465,2996955,5779618,189461396

In [ ]:
''' 
Estados que ficaram de fora da analise:

Rondônia
Acre
Amazonas
Pará
Amapá
Goiás
'''

' \nEstados que ficaram de fora da analise:\n\nRondônia\nAcre\nAmazonas\nPará\nAmapá\nGoiás\n'

In [32]:
merged_df['Percentual_sem_instalacao_sanitaria'] = (merged_df['Não tem instalação sanitária'] / merged_df['Total_saneamento']) 
merged_df['Percentual_utiliza_fossa_rudimentar'] = (merged_df['Fossa rudimendar'] / merged_df['Total_saneamento']) * 100

merged_df.head()

,Unidade da Federação,Cap I_esquistossomose,Total_esquistossomose,Cap I_hepatite,Total_hepatite,Cap I,Total_leptospirose,Rede geral de esgoto ou pluvial,Fossa séptica,Fossa rudimendar,Vala,"Rio, lago ou mar",Outro escoadouro,Não tem instalação sanitária,Total_saneamento,Percentual_sem_instalacao_sanitaria,Percentual_utiliza_fossa_rudimentar
0,21 Maranhão,1.0,1.0,15.0,15.0,2.0,2.0,682546,954029,2963301,529686,53047,419366,945274,6547249,0.144377,45.260246
1,23 Ceará,3.0,3.0,14.0,14.0,8.0,8.0,2645421,893434,3864872,151016,62331,138967,646375,8402416,0.076927,45.997151
2,24 Rio Grande do Norte,3.0,3.0,4.0,4.0,2.0,2.0,764356,624338,1607500,46241,11012,37584,59803,3150834,0.018980,51.018238
3,25 Paraíba,15.0,15.0,4.0,4.0,3.0,3.0,1436381,354990,1452847,148451,52419,80054,219624,3744766,0.058648,38.796737
4,26 Pernambuco,195.0,195.0,22.0,22.0,28.0,28.0,3651981,1003960,2760036,387506,271782,191588,475855,8742708,0.054429,31.569578

In [33]:
corr_esqui_IS = merged_df[['Total_esquistossomose', 'Percentual_sem_instalacao_sanitaria']].corr().iloc[0, 1]
corr_hep_IS = merged_df[['Total_hepatite', 'Percentual_sem_instalacao_sanitaria']].corr().iloc[0, 1]
corr_lepto_IS = merged_df[['Total_leptospirose', 'Percentual_sem_instalacao_sanitaria']].corr().iloc[0, 1]

print(corr_esqui_IS)
print(corr_hep_IS)
print(corr_lepto_IS)

-0.012154033980600751
-0.06399261404206008
-0.10579840628561413

In [34]:
corr_esqui_FR = merged_df[['Total_esquistossomose', 'Percentual_utiliza_fossa_rudimentar']].corr().iloc[0, 1]
corr_hep_FR = merged_df[['Total_hepatite', 'Percentual_utiliza_fossa_rudimentar']].corr().iloc[0, 1]
corr_lepto_FR = merged_df[['Total_leptospirose', 'Percentual_utiliza_fossa_rudimentar']].corr().iloc[0, 1]

print(corr_esqui_FR)
print(corr_hep_FR)
print(corr_lepto_FR)

-0.22163200228745222
-0.210868048502192
-0.27643107749919643